### ISSUE TITLE
Help Running Demo Code on Pico (RP2040)

### ISSUE THREAD

**Issue by j-broome** [RT-Thread-packages/freemodbus#23]
Created RT-Thread Studio project with BSP for Pico/RP2040. I am able to flash the blink demo on the Raspberry Pi Pico. Then I go to settings and follow the steps to add the freemodbus package (including the master and slave demos). Now I can update the package and build. Am I missing something at this point? My main.c is still the blink demo code. Should I be able to run the demos without adding anything to the main code? See images below. Also, I don't want to create an "issue" if there is not one, so what is the recommended way to discuss a potential issue before creating one? 

Workspace after build:
![image](https://user-images.githubusercontent.com/119015958/213544195-d41872f2-0e88-4441-a30b-439572a29253.png)

Freemodbus package setttings:
![image](https://user-images.githubusercontent.com/119015958/213544861-2686c5e8-969e-4698-8987-27eec24781de.png)

**Comment by mysterywolf** [comment]
Hi, in version 5.0.0-dev, we modified `ALIGN` as `rt_align`, or you can enable this:
![image](https://user-images.githubusercontent.com/34888354/213608600-de2dc599-5f81-473e-b9fc-b8af865647d4.png)

**Comment by mysterywolf** [comment]
Thanks for the report, I have fixed this problem at here: https://github.com/RT-Thread-packages/freemodbus/commit/6b1e88d3499c45858e61ad68310079591d725cd8

**Comment by j-broome** [comment]
Enabled legacy support and it works like a champ now. Thank you! Can you fix the typos in the demo code ("samlpe"). Here is my RTT setup as well as my PCB that I am striving to get a legit software stack going on. What is the best resource to learn rapidly or get human support? 

https://user-images.githubusercontent.com/119015958/213620568-4d2145b8-ef3d-4a35-885e-a7106b011758.MOV

![image](https://user-images.githubusercontent.com/119015958/213620685-5b2e193f-0c7a-461a-9aef-dd7c26ceb5aa.jpeg)

**Comment by mysterywolf** [comment]
you mean "sample" is not a correct word in this context right?

Here is some documents: https://github.com/RT-Thread/rt-thread/tree/master/documentation

**Comment by j-broome** [comment]
![image](https://user-images.githubusercontent.com/119015958/213622419-8482fec8-0987-43e9-8bf6-fd72fee35be9.jpeg)

Shouldn't this say sample?

**Comment by mysterywolf** [comment]
Oh  I got it ,  thanks!

**Comment by j-broome** [comment]
thanks again for the assistance!
